import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const GRID_COLUMNS = 3;
const GRID_SPACING = 2;
const GRID_ITEM_SIZE = (width - (GRID_COLUMNS + 1) * GRID_SPACING) / GRID_COLUMNS;

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    errorText: {
        fontSize: 16,
        color: '#65676b',
        marginTop: 12,
    },
    coverSection: {
        position: 'relative',
        backgroundColor: '#f0f2f5',
    },
    coverPhoto: {
        width: '100%',
        height: 200,
        backgroundColor: '#e4e6eb',
    },
    editCoverButton: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profilePictureWrapper: {
        alignItems: 'center',
        marginTop: -50,
        marginBottom: 12,
        position: 'relative',
    },
    profilePicture: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 4,
        borderColor: '#fff',
        backgroundColor: '#e4e6eb',
    },
    editPictureButton: {
        position: 'absolute',
        bottom: 4,
        right: '35%',
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#1877f2',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#fff',
    },
    infoSection: {
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e4e6eb',
    },
    displayName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#050505',
        marginBottom: 4,
    },
    username: {
        fontSize: 15,
        color: '#65676b',
        marginBottom: 12,
    },
    bio: {
        fontSize: 15,
        color: '#050505',
        textAlign: 'center',
        marginBottom: 16,
        paddingHorizontal: 20,
        lineHeight: 20,
    },
    stats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        paddingVertical: 16,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#e4e6eb',
        marginBottom: 16,
    },
    statItem: {
        alignItems: 'center',
    },
    statValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#050505',
    },
    statLabel: {
        fontSize: 14,
        color: '#65676b',
        marginTop: 4,
    },
    actions: {
        flexDirection: 'row',
        gap: 8,
        width: '100%',
        marginTop: 12,
    },
    editButton: {
        flex: 1,
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: '#e4e6eb',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
    },
    editButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#050505',
    },
    logoutButton: {
        flex: 1,
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: '#f02849',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
    },
    logoutButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
    followButton: {
        flex: 1,
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: '#1877f2',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
    },
    followButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
    followingButton: {
        backgroundColor: '#e4e6eb',
    },
    followingButtonText: {
        color: '#050505',
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 8,
        backgroundColor: '#f0f2f5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    postsSection: {
        paddingTop: 16,
    },
    postsSectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#050505',
    },
    tabButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    tabButton: {
        width: 40,
        height: 40,
        borderRadius: 8,
        backgroundColor: '#f0f2f5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabButtonActive: {
        backgroundColor: '#e7f3ff',
    },
    loadingPosts: {
        padding: 40,
        alignItems: 'center',
    },
    emptyPosts: {
        padding: 40,
        alignItems: 'center',
    },
    emptyPostsText: {
        fontSize: 15,
        color: '#65676b',
        marginTop: 12,
    },
    gridContainer: {
        paddingBottom: 20,
    },
    gridRow: {
        gap: GRID_SPACING,
        paddingHorizontal: GRID_SPACING,
        marginBottom: GRID_SPACING,
    },
    gridItem: {
        width: GRID_ITEM_SIZE,
        height: GRID_ITEM_SIZE,
        position: 'relative',
        backgroundColor: '#f0f2f5',
    },
    gridImage: {
        width: '100%',
        height: '100%',
    },
    gridTextPost: {
        width: '100%',
        height: '100%',
        padding: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e7f3ff',
    },
    gridTextContent: {
        fontSize: 11,
        color: '#050505',
        textAlign: 'center',
    },
    gridOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.3)',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
        opacity: 0,
    },
    gridStat: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    gridStatText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '600',
    },
});
